- name: Installing Python
  hosts: localhost
  become: yes
  tasks:
  - name: Check if Python 3 is installed
    ansible.builtin.raw: which python3
    register: python_check
    ignore_errors: yes
    changed_when: false
  
  - name: Log the skipping status
    ansible.builtin.debug:
      msg: "Skipping rest of execution as python3 is already installed."
    when: python_check.rc == 0
  
  - name: cheecking status
    ansible.builtin.meta: end_host
    when: python_check.rc == 0
  

  - name: Installing Python
    ansible.builtin.debug:
      msg: Installing Python
  - name: Python Installation
    ansible.builtin.dnf:
      name: python3
      state: present
    when: python_check.rc != 0