- name: gathering facts
  connection: local
  hosts: Node-1

  tasks:
  - name: Gathering all the facts
    ansible.builtin.shell: cat /etc/passwd
    register: output
  
  - name: print output
    debug:
      msg: "{{ output.stdout }}"