- name: when conditions
  connection: local
  hosts: local
  become: yes
  vars:
    TOPICS:
    - Linux
    - Shell
    - Ansible
    - Terraform
  tasks:
  - name: Greeting
  ansible.builtin.debug:
    msg: 'Hi Vihari, {{ GREETING }}'
