- name: Configuring mongodb
  hosts: target
  become: yes
  tasks:
  - name: Installing mongodb
    ansible.builtin.dnf:
      name: mongodb-org
      state: present
  - name: enabling mongodb service
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes