- name: demo on loops
  connection: local
  become: yes
  hosts: Node-1
  tasks:
  - name: Installing Packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
      - nginx
      - mysql
      - http
